[build]
    base = "gridsome-airtable/"
    publish = "dist/"
    command = "npm run build"

[dev]
    framework = "#custom"
    command = "npm run develop"
    targetPort = 3334
    port = 8888

[[redirects]]
    from = "/editorials/"
    to = "/editorials"
    status = 200
    force = true
